# Tweets Dataset

In [ ]:
# NOTE: This script was intended for use in Google Colab. In order for the cells to run properly on local, you will need to modify
# some of the commands to reference local files as needed.
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

Mounted at /content/drive

In [ ]:
tweets_df = pd.read_csv('/content/drive/MyDrive/CS425-NLP project/datasets/BERT-emotional classifier/emotion_tweets_github.csv')
# tweets_df = pd.read_csv('/content/drive/MyDrive/Acads/Y3 Sem1/CS425 NLC/CS425-NLP project/datasets/BERT-emotional classifier/emotion_tweets_github.csv')
tweets_df

,tweet_id,sentiment,author,content
0,1956967341,empty,xoshayzers,@tiffanylue i know i was listenin to bad habi...
1,1956967666,sadness,wannamama,Layin n bed with a headache ughhhh...waitin o...
2,1956967696,sadness,coolfunky,Funeral ceremony...gloomy friday...
3,1956967789,enthusiasm,czareaquino,wants to hang out with friends SOON!
4,1956968416,neutral,xkilljoyx,@dannycastillo We want to trade with someone w...
...,...,...,...,...
39995,1753918954,neutral,showMe_Heaven,@JohnLloydTaylor
39996,1753919001,love,drapeaux,Happy Mothers Day All my love
39997,1753919005,love,JenniRox,Happy Mother's Day to all the mommies out ther...
39998,1753919043,happiness,ipdaman1,@niariley WASSUP BEAUTIFUL!!! FOLLOW ME!! PEE...
39999,1753919049,love,Alpharalpha,@mopedronin bullet train from tokyo the gf ...

In [ ]:
#Check frequency
tweets_df['sentiment'].value_counts()

neutral       8638
worry         8459
happiness     5209
sadness       5165
love          3842
surprise      2187
fun           1776
relief        1526
hate          1323
empty          827
enthusiasm     759
boredom        179
anger          110
Name: sentiment, dtype: int64

In [ ]:
## Remove Handles

def clean_text(X):
    X = X.split()
    X_new = [x for x in X if not x.startswith("@")]
    return ' '.join(X_new)

tweets_df['text'] = tweets_df['content'].apply(clean_text)
tweets_df

,tweet_id,sentiment,author,content,text
0,1956967341,empty,xoshayzers,@tiffanylue i know i was listenin to bad habi...,i know i was listenin to bad habit earlier and...
1,1956967666,sadness,wannamama,Layin n bed with a headache ughhhh...waitin o...,Layin n bed with a headache ughhhh...waitin on...
2,1956967696,sadness,coolfunky,Funeral ceremony...gloomy friday...,Funeral ceremony...gloomy friday...
3,1956967789,enthusiasm,czareaquino,wants to hang out with friends SOON!,wants to hang out with friends SOON!
4,1956968416,neutral,xkilljoyx,@dannycastillo We want to trade with someone w...,We want to trade with someone who has Houston ...
...,...,...,...,...,...
39995,1753918954,neutral,showMe_Heaven,@JohnLloydTaylor,
39996,1753919001,love,drapeaux,Happy Mothers Day All my love,Happy Mothers Day All my love
39997,1753919005,love,JenniRox,Happy Mother's Day to all the mommies out ther...,Happy Mother's Day to all the mommies out ther...
39998,1753919043,happiness,ipdaman1,@niariley WASSUP BEAUTIFUL!!! FOLLOW ME!! PEE...,WASSUP BEAUTIFUL!!! FOLLOW ME!! PEEP OUT MY NE...
39999,1753919049,love,Alpharalpha,@mopedronin bullet train from tokyo the gf ...,bullet train from tokyo the gf and i have been...

In [ ]:
## drop empty rows in df
tweets_df = tweets_df.drop(tweets_df.index[[tweets_df[tweets_df['text'] == ''].index]])

/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py:4616: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  result = getitem(key)

## Relabel Tweets Dataset


| Label | Original Dataset | New Labelled Dataset |
| :---  |    :----:        |          ---:        | 
| 0 | happiness, love, fun, surprise, relief, enthusiasm | joy |
| 1 | sadness  | sadness | 
| 2 | anger, hate | anger | 
| 3 | worry | fear | 
| 4 | neutral, boredom, empty | neutral |

In [ ]:
## rename column name
tweets_df = pd.DataFrame(tweets_df, columns = ['text','sentiment'])
tweets_df = tweets_df.rename(columns={"sentiment": "label"})

## Relabel
tweets_df['label'] = tweets_df['label'].map({'happiness':0, 'love':0, 'fun':0, 'worry':3, 'empty':4, 'surprise':0, 'sadness':1, 'hate':2, 'anger': 2, 'boredom':4, 'relief': 0, 'enthusiasm':0, 'neutral':4})

In [ ]:
## Sample 50% of "Joy" data
tweets_df_joy = tweets_df.loc[tweets_df['label'] == 0]
tweets_df_joy = tweets_df_joy.sample(frac = 0.6)

tweets_df = tweets_df.loc[tweets_df['label'] != 0]

frames_tweets = [tweets_df, tweets_df_joy]
tweets_df = pd.concat(frames_tweets).reset_index(drop=True)
tweets_df

                                                    text  label
0      i know i was listenin to bad habit earlier and...      4
1      Layin n bed with a headache ughhhh...waitin on...      1
2                    Funeral ceremony...gloomy friday...      1
3      We want to trade with someone who has Houston ...      4
4      Re-pinging why didn't you go to prom? BC my bf...      3
...                                                  ...    ...
33799  finally Mike0hh's birthday &lt;3 can't wait to...      0
33800  houstatlantavegas, sooner than later, nov. 18t...      0
33801                    Its so nice i ahd to work today      0
33802  Haven't been on in foreverr! Almost happy moth...      0
33803  a price drop would be nice I want another one ...      0

[33804 rows x 2 columns]

In [ ]:
#Check frequency
tweets_df['label'].value_counts()

4    9577
0    9178
3    8454
1    5162
2    1433
Name: label, dtype: int64

In [ ]:
import string 

tweets_df['word_count'] = tweets_df['text'].str.split().str.len()

count = lambda l1,l2: sum([1 for x in l1 if x in l2])
tweets_df['punct_count'] = tweets_df['text'].apply(lambda s: count(s, set(string.punctuation)))

tweets_df['total_word_punct_count'] = tweets_df['punct_count'] + tweets_df['word_count']

tweets_df = tweets_df.drop(['punct_count','word_count'], axis=1)
tweets_df = tweets_df.loc[tweets_df['total_word_punct_count'] <= 128].reset_index(drop=True)

tweets_df

,text,label,total_word_punct_count
0,i know i was listenin to bad habit earlier and...,4,19
1,Layin n bed with a headache ughhhh...waitin on...,1,16
2,Funeral ceremony...gloomy friday...,1,9
3,We want to trade with someone who has Houston ...,4,16
4,Re-pinging why didn't you go to prom? BC my bf...,3,18
...,...,...,...
33799,finally Mike0hh's birthday &lt;3 can't wait to...,0,14
33800,"houstatlantavegas, sooner than later, nov. 18t...",0,28
33801,Its so nice i ahd to work today,0,8
33802,Haven't been on in foreverr! Almost happy moth...,0,18
33803,a price drop would be nice I want another one ...,0,17

In [ ]:
# tweets_df.to_csv('/content/drive/MyDrive/Acads/Y3 Sem1/CS425 NLC/CS425-NLP project/datasets/BERT-emotional classifier/emotion_tweets_new.csv')

tweets_df.to_csv('emotional_tweets.csv')
!cp emotional_tweets.csv "/content/drive/MyDrive/CS425-NLP project/datasets/BERT-emotional classifier"

# Import Hugging Face Dataset

*   Reference: https://github.com/huggingface/datasets

In [ ]:
# install datasets
!pip install datasets

# Make sure that we have a recent version of pyarrow in the session before we continue - otherwise reboot Colab to activate it
import pyarrow
if int(pyarrow.__version__.split('.')[1]) < 16 and int(pyarrow.__version__.split('.')[0]) == 0:
    import os
    os.kill(os.getpid(), 9)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: datasets in /usr/local/lib/python3.7/dist-packages (2.6.1)
Requirement already satisfied: fsspec[http]>=2021.11.1 in /usr/local/lib/python3.7/dist-packages (from datasets) (2022.10.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.7/dist-packages (from datasets) (6.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.7/dist-packages (from datasets) (3.8.3)
Requirement already satisfied: responses<0.19 in /usr/local/lib/python3.7/dist-packages (from datasets) (0.18.0)
Requirement already satisfied: dill<0.3.6 in /usr/local/lib/python3.7/dist-packages (from datasets) (0.3.5.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.7/dist-packages (from datasets) (1.21.6)
Requirement already satisfied: pyarrow>=6.0.0 in /usr/local/lib/python3.7/dist-packages (from datasets) (6.0.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.7/dist-packages (from datasets) (0.70.13)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.2.0 in /usr/local/lib/python3.7/dist-packages (from datasets) (0.10.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.7/dist-packages (from datasets) (3.1.0)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.7/dist-packages (from datasets) (2.23.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from datasets) (1.3.5)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from datasets) (4.13.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from datasets) (21.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.7/dist-packages (from datasets) (4.64.1)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (2.1.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (6.0.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (22.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (1.8.1)
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (4.1.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (4.0.2)
Requirement already satisfied: asynctest==0.13.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (0.13.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (1.2.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from huggingface-hub<1.0.0,>=0.2.0->datasets) (3.8.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->datasets) (3.0.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->datasets) (2022.9.24)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->datasets) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->datasets) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->datasets) (2.10)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->datasets) (3.10.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->datasets) (2022.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->datasets) (1.15.0)

In [ ]:
# Let's import the library. We typically only need at most four methods:
from datasets import list_datasets, list_metrics, load_dataset, load_metric

from pprint import pprint

In [ ]:
# Currently available datasets and metrics
datasets = list_datasets()
metrics = list_metrics()

# print(f"ðŸ¤© Currently {len(datasets)} datasets are available on the hub:")
# pprint(datasets, compact=True)
# print(f"ðŸ¤© Currently {len(metrics)} metrics are available on the hub:")
# pprint(metrics, compact=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: list_metrics is deprecated and will be removed in the next major version of datasets. Use 'evaluate.list_evaluation_modules' instead, from the new library ðŸ¤— Evaluate: https://huggingface.co/docs/evaluate
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
# You can access various attributes of the datasets before downloading them
emotion_dataset = list_datasets(with_details=True)[datasets.index('emotion')]
pprint(emotion_dataset.__dict__)  # It's a simple python dataclass

{'_id': '621ffdd236468d709f181e16',
 'author': None,
 'cardData': {'annotations_creators': ['machine-generated'],
              'language': ['en'],
              'language_creators': ['machine-generated'],
              'license': ['unknown'],
              'multilinguality': ['monolingual'],
              'paperswithcode_id': 'emotion',
              'pretty_name': 'Emotion',
              'size_categories': ['10K<n<100K'],
              'source_datasets': ['original'],
              'tags': ['emotion-classification'],
              'task_categories': ['text-classification'],
              'task_ids': ['multi-class-classification'],
              'train-eval-index': [{'col_mapping': {'label': 'target',
                                                    'text': 'text'},
                                    'config': 'default',
                                    'metrics': [{'name': 'Accuracy',
                                                 'type': 'accuracy'},
                                                {'args': {'average': 'macro'},
                                                 'name': 'F1 macro',
                                                 'type': 'f1'},
                                                {'args': {'average': 'micro'},
                                                 'name': 'F1 micro',
                                                 'type': 'f1'},
                                                {'args': {'average': 'weighted'},
                                                 'name': 'F1 weighted',
                                                 'type': 'f1'},
                                                {'args': {'average': 'macro'},
                                                 'name': 'Precision macro',
                                                 'type': 'precision'},
                                                {'args': {'average': 'micro'},
                                                 'name': 'Precision micro',
                                                 'type': 'precision'},
                                                {'args': {'average': 'weighted'},
                                                 'name': 'Precision weighted',
                                                 'type': 'precision'},
                                                {'args': {'average': 'macro'},
                                                 'name': 'Recall macro',
                                                 'type': 'recall'},
                                                {'args': {'average': 'micro'},
                                                 'name': 'Recall micro',
                                                 'type': 'recall'},
                                                {'args': {'average': 'weighted'},
                                                 'name': 'Recall weighted',
                                                 'type': 'recall'}],
                                    'splits': {'eval_split': 'test',
                                               'train_split': 'train'},
                                    'task': 'text-classification',
                                    'task_id': 'multi_class_classification'}]},
 'citation': '@inproceedings{saravia-etal-2018-carer,\n'
             '    title = "{CARER}: Contextualized Affect Representations for '
             'Emotion Recognition",\n'
             '    author = "Saravia, Elvis  and\n'
             '      Liu, Hsien-Chi Toby  and\n'
             '      Huang, Yen-Hao  and\n'
             '      Wu, Junlin  and\n'
             '      Chen, Yi-Shin",\n'
             '    booktitle = "Proceedings of the 2018 Conference on Empirical '
             'Methods in Natural Language Processing",\n'
             '    month = oct # "-" # nov,\n'
             '    year = "2018",\n'
             '    address = "Brussels, Belgium",\n'
             '    publisher = "Association for Computational Linguistics",\n'
             '    url = "https://www.aclweb.org/anthology/D18-1404",\n'
             '    doi = "10.18653/v1/D18-1404",\n'
             '    pages = "3687--3697",\n'
             '    abstract = "Emotions are expressed in nuanced ways, which '
             'varies by collective or individual experiences, knowledge, and '
             'beliefs. Therefore, to understand emotion, as conveyed through '
             'text, a robust mechanism capable of capturing and modeling '
             'different linguistic nuances and phenomena is needed. We propose '
             'a semi-supervised, graph-based algorithm to produce rich '
             'structural descriptors which serve as the building blocks for '
             'constructing contextualized affect representations from text. '
             'The pattern-based representations are further enriched with word '
             'embeddings and evaluated through several emotion recognition '
             'tasks. Our experimental results demonstrate that the proposed '
             'method outperforms state-of-the-art techniques on emotion '
             'recognition tasks.",\n'
             '}',
 'description': 'Emotion is a dataset of English Twitter messages with six '
                'basic emotions: anger, fear, joy, love, sadness, and '
                'surprise. For more detailed information please refer to the '
                'paper.',
 'downloads': 16626,
 'gated': False,
 'id': 'emotion',
 'lastModified': '2022-10-28T16:32:30.000Z',
 'likes': 56,
 'paperswithcode_id': 'emotion',
 'private': False,
 'sha': '091b2f54717936d7183798599d9ef047022f7530',
 'siblings': None,
 'tags': ['annotations_creators:machine-generated',
          'language_creators:machine-generated',
          'language:en',
          'license:unknown',
          'multilinguality:monolingual',
          'size_categories:10K<n<100K',
          'source_datasets:original',
          'task_categories:text-classification',
          'task_ids:multi-class-classification',
          'tags:emotion-classification']}

## Emotion Dataset

In [ ]:
# Downloading and loading a dataset
emotion_dataset = load_dataset('emotion', split='validation[:20%]')

WARNING:datasets.builder:Found cached dataset emotion (/root/.cache/huggingface/datasets/emotion/default/0.0.0/348f63ca8e27b3713b6c04d723efe6d824a56fb3d1449794716c0f0296072705)

In [ ]:
print(emotion_dataset)

Dataset({
    features: ['text', 'label'],
    num_rows: 400
})

In [ ]:
print(emotion_dataset.unique('label'))

[0, 2, 3, 1, 4, 5]

## Empathetic Dialogue Dataset

In [ ]:
empatheticDialogue_dataset = list_datasets(with_details=True)[datasets.index('empathetic_dialogues')]
pprint(empatheticDialogue_dataset.__dict__)

{'_id': '621ffdd236468d709f181e18',
 'author': None,
 'cardData': {'annotations_creators': ['crowdsourced'],
              'language': ['en'],
              'language_creators': ['crowdsourced'],
              'license': ['cc-by-nc-4.0'],
              'multilinguality': ['monolingual'],
              'paperswithcode_id': 'empatheticdialogues',
              'pretty_name': 'EmpatheticDialogues',
              'size_categories': ['10K<n<100K'],
              'source_datasets': ['original'],
              'task_categories': ['conversational', 'question-answering'],
              'task_ids': ['dialogue-generation', 'open-domain-qa']},
 'citation': '@inproceedings{rashkin2019towards,\n'
             '  title = {Towards Empathetic Open-domain Conversation Models: a '
             'New Benchmark and Dataset},\n'
             '  author = {Hannah Rashkin and Eric Michael Smith and Margaret '
             'Li and Y-Lan Boureau},\n'
             '  booktitle = {ACL},\n'
             '  year = {2019},\n'
             '}',
 'description': 'PyTorch original implementation of Towards Empathetic '
                'Open-domain Conversation Models: a New Benchmark and Dataset',
 'downloads': 982,
 'gated': False,
 'id': 'empathetic_dialogues',
 'lastModified': '2022-10-28T16:32:30.000Z',
 'likes': 12,
 'paperswithcode_id': 'empatheticdialogues',
 'private': False,
 'sha': 'd6d39e2a84ddf714fb4caea9d9fe87f9adcffefa',
 'siblings': None,
 'tags': ['arxiv:1811.00207',
          'annotations_creators:crowdsourced',
          'language:en',
          'language_creators:crowdsourced',
          'license:cc-by-nc-4.0',
          'multilinguality:monolingual',
          'size_categories:10K<n<100K',
          'source_datasets:original',
          'task_categories:conversational',
          'task_categories:question-answering',
          'task_ids:dialogue-generation',
          'task_ids:open-domain-qa']}

In [ ]:
empatheticDialogue_dataset = load_dataset('empathetic_dialogues', split='validation[:20%]')

WARNING:datasets.builder:Found cached dataset empathetic_dialogues (/root/.cache/huggingface/datasets/empathetic_dialogues/default/0.1.0/09bbeed3882a67db98c73952fb3c1c9a85af83dc78f81454c2454382fd03f6cf)

In [ ]:
print(empatheticDialogue_dataset)

Dataset({
    features: ['conv_id', 'utterance_idx', 'context', 'prompt', 'speaker_idx', 'utterance', 'selfeval', 'tags'],
    num_rows: 2406
})

In [ ]:
print(empatheticDialogue_dataset.unique('context'))

['terrified', 'surprised', 'excited', 'disgusted', 'caring', 'sentimental', 'sad', 'embarrassed', 'afraid', 'impressed', 'grateful', 'joyful', 'proud', 'hopeful', 'faithful', 'lonely', 'confident', 'annoyed', 'anticipating', 'furious', 'jealous', 'nostalgic', 'apprehensive', 'guilty', 'ashamed', 'prepared', 'anxious', 'content', 'angry', 'devastated', 'trusting', 'disappointed']

# Re-Label Dataset

In [ ]:
import pandas as pd

## Emotion Dataset

| Label | Original Dataset | 
| :---  |    :----:        |
| 0 | sadness | 
| 1 | joy        | 
| 2 | love       | 
| 3 | anger        | 
| 4 | fear       | 
| 5 | surprise |


## Rebelling Emotion Dataset

| Label | Original Dataset Labels | New Labelled Dataset | 
| :---  |    :----:        |          ---:        |
| 0 | joy, love, surprise | joy |
| 1 | sadness | sadness |
| 2 | anger     | anger |
| 3 | fear    | fear |
| 4 | NA      | neutral |

In [ ]:
df_emotion = pd.DataFrame(emotion_dataset, columns = ['text','label'])
df_emotion['label'] = df_emotion['label'].map({0:1, 1:0, 2:0, 3:2, 4:3, 5:0})
df_emotion

                                                  text  label
0    im feeling quite sad and sorry for myself but ...      1
1    i feel like i am still looking at a blank canv...      1
2                       i feel like a faithful servant      0
3                    i am just feeling cranky and blue      2
4    i can have for a treat or if i am feeling festive      0
..                                                 ...    ...
395  i had no particular feelings about him before ...      0
396                         i feel pretty pathetic now      1
397  i cant tell you what this feels like on the fa...      0
398                               i feel rich comments      0
399  i feel like a failure at parenting and each ti...      0

[400 rows x 2 columns]


## Relabel Empathetic Dialogue Dataset


| Label | Original Dataset | New Labelled Dataset | Number of Rows |
| :---  |    :----:        |          ---:        |         ---:        |
| 0 | joyful, content, grateful, proud, confident, nostalgic, trusting, caring, faithful, surprised, impressed, anticipating, hopeful, excited | joy |  |
| 1 |  sad, devastated, sentimental, lonely, disappointed, embarrassed    | sadness |  |
| 2 |  disgusted, ashamed, angry, furious, annoyed, jealous   | anger |  |
| 3 |  terrified, afraid, guilty, anxious, apprehensive       | fear |  |
| 4 |  prepared     | neutral |  |

In [ ]:
df_empatheticDialogue = pd.DataFrame(empatheticDialogue_dataset, 
                          columns = ['conv_id', 'utterance_idx', 'context', 'prompt', 
                                     'speaker_idx', 'utterance', 'selfeval', 'tags'])
df_empatheticDialogue = df_empatheticDialogue[['utterance','context']]
df_empatheticDialogue['context'] = df_empatheticDialogue['context'].map(
    {'joyful':0, 'content':0, 'grateful':0, 'proud':0, 'confident':0, 'nostalgic':0,
     'trusting':0, 'caring':0, 'faithful':0, 
     'terrified':3, 'afraid':3, 'guilty':3, 'anxious':3, 'apprehensive':3,
     'surprised':0, 'embarrassed':1, 'impressed':0,
     'sad':1, 'devastated':1, 'sentimental':1, 'lonely':1, 'disappointed':1, 
     'disgusted':2, 'ashamed':2, 
     'angry':2, 'furious':2, 'annoyed':2, 'jealous':2,
     'anticipating':0, 'hopeful':0, 'prepared':4, 'excited':0 })
df_empatheticDialogue = df_empatheticDialogue.rename({'utterance': 'text', 'context': 'label'}, axis='columns')
df_empatheticDialogue

                                                   text  label
0     Today_comma_as i was leaving for work in the m...      3
1                                     Are you fine now?      3
2     Yeah_comma_i'm doing alright now_comma_ but wi...      3
3                    Cool :) Is your car damaged a lot?      3
4     The car was badly damaged_comma_i veered outsi...      3
...                                                 ...    ...
2401  I recently took my ELS certification test. I s...      0
2402                                        What's ELS?      0
2403  Sorry_comma_ ESL. It's English as a Second Lan...      0
2404  Ah_comma_ gotcha. A few of my friends teach En...      0
2405  I just moved into my new house and I am having...      2

[2406 rows x 2 columns]

In [ ]:
df_empatheticDialogue['text'] = df_empatheticDialogue['text'].replace({'_comma_' : ','}, regex=True)
df_empatheticDialogue

                                                   text  label
0     Today,as i was leaving for work in the morning...      3
1                                     Are you fine now?      3
2     Yeah,i'm doing alright now, but with minor inj...      3
3                    Cool :) Is your car damaged a lot?      3
4     The car was badly damaged,i veered outside the...      3
...                                                 ...    ...
2401  I recently took my ELS certification test. I s...      0
2402                                        What's ELS?      0
2403  Sorry, ESL. It's English as a Second Language....      0
2404  Ah, gotcha. A few of my friends teach English ...      0
2405  I just moved into my new house and I am having...      2

[2406 rows x 2 columns]

# Concatenate Dataframes

In [ ]:
frames = [df_emotion, df_empatheticDialogue]
df_huggingFace = pd.concat(frames).reset_index(drop=True)
df_huggingFace

                                                   text  label
0     im feeling quite sad and sorry for myself but ...      1
1     i feel like i am still looking at a blank canv...      1
2                        i feel like a faithful servant      0
3                     i am just feeling cranky and blue      2
4     i can have for a treat or if i am feeling festive      0
...                                                 ...    ...
2801  I recently took my ELS certification test. I s...      0
2802                                        What's ELS?      0
2803  Sorry, ESL. It's English as a Second Language....      0
2804  Ah, gotcha. A few of my friends teach English ...      0
2805  I just moved into my new house and I am having...      2

[2806 rows x 2 columns]

# Combine Datasets

Total data-size: 62k+ rows
- Hugging Face
- Kaggle 
- Tweets (Github)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df_kaggle = pd.read_csv('/content/drive/MyDrive/CS425-NLP project/datasets/BERT-emotional classifier/emotion_kaggle.csv') 
df_kaggle = df_kaggle.drop('Unnamed: 0', axis=1)
df_kaggle

                                                    text  label
0      im feeling rather rotten so im not very ambiti...      1
1              im updating my blog because i feel shitty      1
2      i never make her separate from me because i do...      1
3      i left with my bouquet of red and yellow tulip...      0
4        i was feeling a little vain when i did this one      1
...                                                  ...    ...
19995  im having ssa examination tomorrow in the morn...      1
19996  i constantly worry about their fight against n...      0
19997  i feel its important to share this info for th...      0
19998  i truly feel that if you are passionate enough...      0
19999  i feel like i just wanna buy any cute make up ...      0

[20000 rows x 2 columns]

In [ ]:
df_datasets = [df_huggingFace, df_kaggle, tweets_df]
df_final = pd.concat(df_datasets).reset_index(drop=True)

In [ ]:
import string

df_final['word_count'] = df_final['text'].str.split().str.len()

count = lambda l1,l2: sum([1 for x in l1 if x in l2])
df_final['punct_count'] = df_final['text'].apply(lambda s: count(s, set(string.punctuation)))

df_final['total_word_punct_count'] = df_final['punct_count'] + df_final['word_count']

df_final = df_final.drop(['punct_count','word_count'], axis=1)
df_final = df_final.loc[df_final['total_word_punct_count'] <= 128].reset_index(drop=True)

df_final

,text,label,total_word_punct_count
0,im feeling quite sad and sorry for myself but ...,1,15
1,i feel like i am still looking at a blank canv...,1,15
2,i feel like a faithful servant,0,6
3,i am just feeling cranky and blue,2,7
4,i can have for a treat or if i am feeling festive,0,12
...,...,...,...
56604,haha best thing about office birthdays hey,0,7
56605,hehe now im smiling... but u still gotta make ...,0,16
56606,"My 100th post- dedicated to Sarah,sunny weathe...",0,29
56607,"Sounds like a good time, very nice of you. Did...",0,33
56608,I'm packed up &amp; leaving my Canterbury offi...,0,35

In [ ]:
#Check frequency
df_final['label'].value_counts()

0    19605
1    11550
3    11237
4     9651
2     4566
Name: label, dtype: int64

# Save Dataset to GDrive

In [ ]:
df_final.to_csv('combined_emotional_data.csv')
!cp combined_emotional_data.csv "/content/drive/MyDrive/CS425-NLP project/datasets/BERT-emotional classifier"

In [ ]:
df_huggingFace.to_csv('emotion_huggingFace.csv')
!cp emotion_huggingFace.csv "/content/drive/MyDrive/CS425-NLP project/datasets/BERT-emotional classifier"

In [ ]:
df_huggingFace.to_csv('emotion_tweets.csv')
!cp emotion_tweets.csv "/content/drive/MyDrive/CS425-NLP project/datasets/BERT-emotional classifier"